version: "3.3"

services:

  feijoadaweek:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek
    hostname: feijoadaweek
    env_file:
      - .env
    environment:
      expose: 8080
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.28.0.10

  feijoadaweek-develop:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek-develop
    hostname: feijoadaweek-develop
    env_file:
      - .env
    environment:
      expose: 8080
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.28.0.11

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
