version: "3.3"

services:

  feijoadaweek:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek
    hostname: feijoadaweek
    env_file:
      - .env
    environment:
      expose: 8080
    restart: unless-stopped

  feijoadaweek-develop:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek-develop
    hostname: feijoadaweek-develop
    env_file:
      - .env
    environment:
      expose: 8080
    restart: unless-stopped
