version: "3.3"

services:

  feijoadaweek:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feijoadaweek
    hostname: feijoadaweek
    environment:
      FEIJUCA_DATABASE_URL: ${FEIJUCA_DATABASE_URL}
      FEIJUCA_DATABASE_USERNAME: ${FEIJUCA_DATABASE_USERNAME}
      FEIJUCA_DATABASE_PASSWORD: ${FEIJUCA_DATABASE_PASSWORD}
      expose: 8080
    restart: unless-stopped
<<<<<<< HEAD

=======
>>>>>>> 5c6899ca795ddb3ac249f4e8a8df3f5165686f4f
